GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "event xdrt",
  "description": "xdrt",
  "date": "2020-01-01T13:00:00",
  "price": 5689
}

###
GET http://localhost:3000/events/ccb6a404-b525-4495-a478-c2c36819e774

###
PATCH   http://localhost:3000/events/ccb6a404-b525-4495-a478-c2c36819e774
Content-Type: application/json

{
  "name": "event qwer",
  "description": "qwer",
  "date": "2020-01-01T13:00:00",
  "price": 5689
}

###
DELETE http://localhost:3000/events/ccb6a404-b525-4495-a478-c2c36819e774