GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "event name",
  "description": "event description",
  "date": "2020-01-01T13:00:00",
  "price": 100
}

###

@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "event name",
  "description": "event description",
  "date": "2020-01-01T13:00:00",
  "price": 100
}

###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "event name edited",
  "description": "event description edited",
  "date": "2022-01-01T13:00:00",
  "price": 1000
}

###
DELETE http://localhost:3000/events/{{eventId}}

###
GET http://localhost:3000/events/{{eventId}}/spots

###
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A1"
}