GET http://localhost:3001/eventos

###
# @name createEvent
POST http://localhost:3001/eventos
Content-Type: application/json

{
  "nome": "event name",
  "descricao": "event description",
  "data": "2020-01-01T13:00:00",
  "preco": 100
}

###

@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3001/eventos/{{eventId}}

###
PATCH http://localhost:3001/eventos/{{eventId}}
Content-Type: application/json

{
  "nome": "event name edited",
  "descricao": "event description edited",
  "data": "2025-01-01T13:00:00",
  "preco": 1000
}

###
DELETE http://localhost:3001/eventos/{{eventId}}





###
GET http://localhost:3001/eventos/{{eventId}}/lugares

###
# @name createSpot
POST http://localhost:3001/eventos/{{eventId}}/lugares
Content-Type: application/json

{
  "nome": "A1"
}

###

@spotName = {{ createSpot.response.body.name }}

###
POST http://localhost:3001/eventos/{{eventId}}/reservar
Content-Type: application/json
X-Api-Token: 1234

{
  "lugares": ["{{ spotName }}"],
  "tipo_ingresso": "FULL",
  "email": "john@doe.com"
}